#!/bin/bash
#this script will delete a user


#Run as root
if [[ "${UID}" -ne 0 ]]
then
        echo 'Please run as a root' >&2
        exit 1
fi

#Assume the first argument is the user to delete
USER="${1}"

#Delete the user
userdel ${USER}

#Make sure the user got deleted
if [[ "${?}" -ne 0 ]]
then
        echo "The account ${USER} is NOT deleted ."
        exit 1
fi

#Tell the user the account is deleted.
echo "The user ${USER} is deleted !"

exit 0
